### ISSUE TITLE
Feature request: Add to existing RRR playlist rather than replacing?

### ISSUE THREAD

**Issue by jeremymeyers** [yboyer/realreleaseradar#166]
Hey there- Would be awesome to have an option to have an ever-growing playlist created rather than removing and replacing each week if that makes sense.

**Comment by yboyer** [comment]
Hello 👋  Sorry for the delay 😅
I prefer to have the same logic of the official release radar from Spotify. The playlist size limit is 10,000 so it can quickly be reached for some users if the playlist isn't cleaned up..
